language: node_js
node_js:
- '8'
before_install:
- npm i -g npm@6.1.0
install:
- npm install
script:
- npm run lint
- npm run unit
- npm run build
deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      all_branches: true
