language: node_js
node_js:
- '8'
cache:
  directories:
    - node_modules
before_install:
- npm i -g npm@6.1.0
install:
- travis_wait npm install
before_deploy:
- export TARGET_DEVICE=`[[ $TRAVIS_BRANCH =~ ^(master|develop)$ ]] && echo "desktop"`
- npm run build
deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      all_branches: true
